name: Bug report
description: Report a problem you found in the Inazuma Guide Wiki
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us keep the Inazuma Guide stable. Please use this form for UI issues, broken data views, or any feature that stops working.

        Before opening a new report:
        1. Reload the page to confirm it is not a caching problem.
        2. Search existing issues to avoid duplicates.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead. Screenshots or short clips help a lot.
      placeholder: |
        When opening the Players page I expected the stat filters to show...

        Instead, I saw...
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Include clear steps so we can reproduce quickly.
      placeholder: |
        1. Open the guide
        2. Go to Equipments
        3. Toggle sorting by Pressure
        4. Sorting gets stuck on loading...
  - type: textarea
    id: app-logs
    attributes:
      label: Anything else we should know?
      description: Optional notes, screenshots, or recorded GIFs that help illustrate the issue.
  - type: dropdown
    id: os-platform
    attributes:
      label: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Arc
        - Brave
        - Other
  - type: dropdown
    id: feature-area
    attributes:
      label: Which feature area does this bug affect?
      options:
        - Players database
        - Equipments database
        - Hissatsu catalog
        - Team builder / formations
        - Changelog & wiki
        - UI & navigation
        - Local storage / state
        - Other
    validations:
      required: true
